services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: conttrade-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:3006/api/v1}
      JWT_SECRET: ${JWT_SECRET:-your-jwt-secret-key-change-in-production}
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

